name: docker

on:
  push:
    branches:
      - "docker"

jobs:
  build_and_push_server_dev_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          target: builder
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/immich-server-dev:latest

  build_and_push_machine_learning_dev_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./machine-learning
          file: ./machine-learning/Dockerfile
          target: builder
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/immich-machine-learning-dev:latest
